language: python
sudo: false
python:
  - "3.6"
install:
  - pip install -r requirements-dev.txt
  - pip install git+https://github.com/didadadida93/primordial.git
script:
  - coverage run -m unittest discover
after_success:
  - codecov
